# Generated by Django 5.0.3 on 2024-03-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_special_room_room_archive_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
        migrations.AlterField(
            model_name='room',
            name='exam_collection_room',
            field=models.BooleanField(default=False, verbose_name='Coleta de Exames'),
        ),
    ]
